### ISSUE TITLE
User Trip Show Page

### ISSUE THREAD

**Issue by SandyyMarie** [TripWeather/trip_weather_fe#13]
As a User,
When I visit the trip show page,
I see the trip name, departure location, destination, trip date and time, real time weather status, and trip status 
If the trip date is too far out I will see a message that says "weather is not available yet"
If the trip status is "completed" then I will see the user trip log for that trip 
I see a section for "Friends on this Trip" where I see a list of all friends invited on this trip. 
If there are no friends invited for this trip I will see a message 
that says "No Friends Currently Invited"

**Comment by eriggs0207** [comment]
No friends functionality completed
